[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
always_use_create_2_factory = true
create2_deployer = "0x4e59b44847b379578588920ca78fbf26c0b4956c"
solc_version = "0.8.30"

memory_limit = 1342177280
optimizer_runs = 600
# dynamic_test_linking = true
# Auto-detect Solidity versions from pragma statements
auto_detect_solc = true
ffi = true 

fs_permissions = [
    { access = "read", path = "./out"},
    { access = "read-write", path = "../frontend/public/powered/" }
]

# Remappings for dependencies
# NOTE: Order matters! More specific remappings should come first
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@lib/openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@lib/powers-monorepo/=lib/powers-monorepo/",
    "@lib/safe-smart-account/=lib/safe-smart-account/",
    "@lib/account-abstraction/=lib/powers-monorepo/solidity/lib/account-abstraction/",
    "@lib/forge-std/=lib/forge-std/",
    "@lib/zkpassport-packages/=lib/powers-monorepo/solidity/lib/zkpassport-packages/",
    "@lib/chainlink-evm/=lib/chainlink-evm/",
    "@mocks/=lib/powers-monorepo/solidity/test/mocks/",
    "@src/=lib/powers-monorepo/solidity/src/",
    "@script/=lib/powers-monorepo/solidity/script",
    "@governance-monorepo/=lib/powers-monorepo/solidity/governance/",
    "forge-std/=lib/powers-monorepo/solidity/lib/forge-std/src/",
    "@governance/=governance/"
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = false

[fuzz]
runs = 256
depth = 256
fail_on_revert = true 
seed = '0x4ea'

[invariant] 
runs = 32
depth = 32 
fail_on_revert = true 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
